version: '3'

services:
  database:
    container_name: database
    image: postgres:13
    ports: 
      - $DB_PORT:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      